version: "3.1"
services:
    postgres:
        image: postgres:13.1-alpine
        restart: always
        environment:
            POSTGRES_USER: actix
            POSTGRES_PASSWORD: actix
            POSTGRES_DB: actix
        ports:
            - 5432:5432
        deploy:
            resources:
                limits:
                    memory: '512M'
                    cpus: '1'
    todo-actix:
        build: .
        links:
            - postgres
        env_file:
            - docker.env
        deploy:
            resources:
                limits:
                    memory: '512M'
                    cpus: '1'
        ports:
            - 8080:8080
